### ISSUE TITLE
Icons 

### ISSUE THREAD

**Issue by ahmedlhanafy** [react-native-paper/react-native-paper#21]
We will use [react-native-vector-icons](https://github.com/oblador/react-native-vector-icons) but this component needs to implement touchable component that has ripple effects cross-platform 
and It needs to have [Tooltips](https://material.google.com/components/tooltips.html#)
[MD Docs Link](https://material.google.com/style/icons.html)

**Comment by geminiyellow** [comment]
`tooltip` is a good idea, not binding with icon.
