### ISSUE TITLE
Unexpected Token Error in src/index.js

### ISSUE THREAD

**Issue by sreejithr** [react-native-paper/react-native-paper#91]
I just imported from react-native-paper and this happened:

```
<path-to-project>/node_modules/react-native-paper/src/index.js: Unexpected token (6:9) at index.js:6:9
```

Seems like this line is the culprit:

```
export * as Colors from './styles/colors';
```
I fixed it by adding installing [babel-plugin-transform-export-extensions](http://babeljs.io/docs/plugins/transform-export-extensions/) and adding `transform-export-extensions` babel plugin in my `.babelrc`.

Shouldn't this plugin be added as default?

### Versions
1. react-native: `0.37.0`.
2. react-native-paper: `0.0.2` (Latest `master` also has the issue)

**Comment by satya164** [comment]
You can use the `react-native-stage-0` preset. But we should change that. The lib should be usable without having to add a custom preset.

We need to change it to,

```js
import * as Colors from './styles/colots';

export Colors;
```
